# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BaseBuild
  timeoutInMinutes: 5
  strategy:
    matrix:
      linux:
        name: 'linux'
        arch: 'x64'
        imageName: 'ubuntu-16.04'
        extension: ''
      mac:
        name: 'mac'
        arch: 'x64'
        imageName: 'macos-10.13'
        extension: ''
      win64:
        name: 'win64'
        arch: 'x64'
        imageName: 'vs2017-win2016'
        extension: '.exe'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UseNode@1
    inputs:
      version: '12.x'

  - script: |
      npm install nexe --global
      yarn install
    displayName: 'prepare'

  #- script: |
  #    yarn pkg-$(name)
  #    echo 'Done'
  - script: nexe index.js --output $(Build.BinariesDirectory)/bin/$(name)/picgo$(extension)
    displayName: 'package'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/bin/$(name)/'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(name).zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/'
      artifact: 'picgo-cli-$(name)'
      publishLocation: 'pipeline'

  - script: |
      ls -a $(System.ArtifactsDirectory)
      ls -a $(Build.ArtifactStagingDirectory)
    displayName: 'check result'

- job: Release
  dependsOn: BaseBuild

  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'specific'
      downloadPath: '$(System.ArtifactsDirectory)'
  
  - script: |
      ls -a $(System.ArtifactsDirectory)
      ls -a $(Build.ArtifactStagingDirectory)
    displayName: 'check result'

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_abnerlee'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      target: '$(Build.SourceVersion)'
      tag: 'latest'
      assetUploadMode: 'replace'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'