# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BaseBuild
  timeoutInMinutes: 360
  strategy:
    matrix:
      linux:
        name: 'linux'
        arch: 'x64'
        imageName: 'ubuntu-16.04'
      mac:
        name: 'mac'
        arch: 'x64'
        imageName: 'macos-10.13'
      win64:
        name: 'win64'
        arch: 'x64'
        imageName: 'vs2017-win2016'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UseNode@1
    inputs:
      version: '12.x'

  - script: |
      yarn add nexe -D 
      yarn install
    displayName: 'prepare'

  - script: |
      yarn pkg-$(name)
    displayName: 'package'

  