version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: echo "start build"
      - run: yarn add nexe -D 
      - run: yarn install
      - run: yarn pkg-win64
      - run: yarn pkg-win32
      - run: yarn pkg-mac
      - run: yarn pkg-linux
      - run: echo "Pkg to binary Done"
      - run: ls -a bin/
      - persist_to_workspace:
          root: .
          paths: 
            - .
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g')
            echo ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/
      - run: echo "Release Done"

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
